# Spring Data MongoDB Configuration
# Connected to MongoDB Atlas cluster 'HospitalManagement'
spring.data.mongodb.uri=mongodb://localhost:27017/GlobalHospital

# Application Server Port
server.port=8080

# Logging config
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.web=INFO
